public class PrimitiveTypes
{
    public Blob MyBlob = Blob.valueOf('Jay');
    public Boolean IsWinner = true;
    public Date MyDate = Date.today();
    public DateTime MyDateTime = DateTime.now();
    public Decimal MyDecimal = 12.4567;
    public Double d=3.133433;
    public ID MyId = '006E0000004TquXIAS';
    public Integer MyInteger = 1;
    public Long MyLong = 23432424242L;
    public Time MyTime = Time.newInstance(1, 2, 3, 4);
    public String MyString = 'Jay';

    public Object obj = 10;
    public Integer i = (Integer)obj;
}